# Generated by Django 5.2.4 on 2026-05-22 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_title',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='method',
            field=models.CharField(choices=[('JazzCash', 'JazzCash'), ('EasyPaisa', 'EasyPaisa'), ('Bank', 'Bank Transfer')], default='JazzCash', max_length=20),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('source', models.CharField(choices=[('login_bonus', 'Daily Login Bonus'), ('task', 'Task Reward'), ('referral', 'Referral Commission'), ('spin', 'Spin Reward'), ('ad', 'Ad Reward'), ('withdrawal', 'Withdrawal'), ('admin', 'Admin Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
