"""
Django settings for earning_site project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-(yir6f7mj&dj5@=cz2!834&k9uqpck-8=)fdtvj#nneyh9l0)w')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [host.strip() for host in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'django.contrib.humanize',

    # Your apps
    'accounts.apps.AccountsConfig',
    'plans',
    'ads',
    'wallet',
    'payments',
    'rewards.apps.RewardsConfig',
]

LOGIN_URL = '/login/'
# settings.py
LOGIN_URL = '/login/'  # or whatever your login route is

# settings.py
LOGIN_URL = '/login/'  # or whatever your login route is
LOGIN_URL = '/login/'
# or wherever the user should go after login


JAZZCASH_MERCHANT_ID = "your_merchant_id"
JAZZCASH_PASSWORD = "your_password"
JAZZCASH_SALT = "your_salt"
# settings.py

JAZZCASH_MERCHANT_ID = 'YourMerchantID'
JAZZCASH_PASSWORD = 'YourPassword'
JAZZCASH_SALT = 'YourSecureHashSalt'
JAZZCASH_RETURN_URL = 'https://yourdomain.com/payment/verify-otp/'


EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For testing in console
DEFAULT_FROM_EMAIL = 'no-reply@yourdomain.com'
AUTH_USER_MODEL = 'accounts.CustomUser'  # or your actual user model path
# Replace with your sandbox credentials
JAZZCASH_MERCHANT_ID = 'YOUR_SANDBOX_MERCHANT_ID'
JAZZCASH_PASSWORD = 'YOUR_SANDBOX_PASSWORD'
JAZZCASH_SALT = 'YOUR_SANDBOX_SALT'
# settings.py
TWILIO_ACCOUNT_SID = 'your_sid'
TWILIO_AUTH_TOKEN = 'your_auth_token'
TWILIO_PHONE_NUMBER = '+1234567890'
TWILIO_ACCOUNT_SID = 'ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
TWILIO_AUTH_TOKEN = 'your_auth_token_here'
TWILIO_PHONE_NUMBER = '+1XXXXXXXXXX'  # from Twilio dashboard

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'rewards.middleware.SimpleRateLimitMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'rewards.middleware.AuditLogMiddleware',
    'rewards.middleware.SecurityHeadersMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'earning_site.urls'

AUTH_USER_MODEL = 'accounts.CustomUser'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # ✅ Add this line
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'earning_site.wsgi.application'


# Database
# Use DATABASE_URL=postgres://USER:PASSWORD@HOST:5432/DBNAME in production.
DATABASE_URL = os.getenv('DATABASE_URL', '')
if DATABASE_URL.startswith(('postgres://', 'postgresql://')):
    from urllib.parse import urlparse
    parsed_db = urlparse(DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed_db.path.lstrip('/'),
            'USER': parsed_db.username,
            'PASSWORD': parsed_db.password,
            'HOST': parsed_db.hostname,
            'PORT': parsed_db.port or 5432,
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SECURE = os.getenv('DJANGO_SECURE_COOKIES', 'False') == 'True'
CSRF_COOKIE_SECURE = os.getenv('DJANGO_SECURE_COOKIES', 'False') == 'True'
SECURE_SSL_REDIRECT = os.getenv('DJANGO_SSL_REDIRECT', 'False') == 'True'
SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_HSTS_SECONDS', '0'))

PAYMENT_GATEWAY_MODE = os.getenv('PAYMENT_GATEWAY_MODE', 'manual_otp')
JAZZCASH_MERCHANT_ID = os.getenv('JAZZCASH_MERCHANT_ID', JAZZCASH_MERCHANT_ID)
JAZZCASH_PASSWORD = os.getenv('JAZZCASH_PASSWORD', JAZZCASH_PASSWORD)
JAZZCASH_SALT = os.getenv('JAZZCASH_SALT', JAZZCASH_SALT)
EASYPAISA_STORE_ID = os.getenv('EASYPAISA_STORE_ID', '')
EASYPAISA_HASH_KEY = os.getenv('EASYPAISA_HASH_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
CPX_RESEARCH_APP_ID = os.getenv('CPX_RESEARCH_APP_ID', '')
OFFERTORO_APP_ID = os.getenv('OFFERTORO_APP_ID', '')
ADGEM_APP_ID = os.getenv('ADGEM_APP_ID', '')
VPN_DETECTION_API_KEY = os.getenv('VPN_DETECTION_API_KEY', '')

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_BEAT_SCHEDULE = {
    'fraud-velocity-scan-every-10-minutes': {
        'task': 'rewards.tasks.scan_fraud_velocity',
        'schedule': 600.0,
    },
    'withdrawal-queue-check-every-15-minutes': {
        'task': 'rewards.tasks.process_withdrawal_queue',
        'schedule': 900.0,
    },
}

REDIS_URL = os.getenv('REDIS_URL', '')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }

CSP_DEFAULT_SRC = os.getenv('CSP_DEFAULT_SRC', "'self'")
CSP_SCRIPT_SRC = os.getenv('CSP_SCRIPT_SRC', "'self' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com")
CSP_STYLE_SRC = os.getenv('CSP_STYLE_SRC', "'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com")
CSP_FONT_SRC = os.getenv('CSP_FONT_SRC', "'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com")
CSP_IMG_SRC = os.getenv('CSP_IMG_SRC', "'self' data:")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
